data_augmentation:
  copy_paste: 0.0
  degrees: 0.0
  fliplr: 0.5
  flipud: 0.0
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  mixup: 0.0
  mosaic: 1.0
  perspective: 0.0
  scale: 0.5
  shear: 0.0
  translate: 0.1
model:
  freeze_layers: null
  pretrained: true
  size: n
optimization:
  close_mosaic: 10
  device: auto
  exist_ok: false
  name: helmet_detection_professional
  optimizer: auto
  pretrained: true
  project: runs/detect
  workers: 8
training:
  batch_size: 16
  epochs: 100
  image_size: 640
  learning_rate: 0.01
  momentum: 0.937
  patience: 50
  save_period: 10
  weight_decay: 0.0005
validation:
  plots: true
  save_hybrid: false
  save_json: true
  val: true
